import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/ui/Header/Header";
import Footer from "./components/ui/Footer/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        style={{
          display: "grid",
          gridTemplateRows: "auto 1fr auto",
          minHeight: "100vh",
        }}
      >
        <Header />
        <main className="bg-gradient-to-r from-rose-300 via-emerald-300  to-cyan-950 dark:bg-lime-600">{children}</main>
        <Footer />
      </body>
    </html>
  );
}