import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/ui/Header/Header";
import Footer from "./components/ui/Footer/Footer";

export const metadata: Metadata = {
  title: "InfoNews",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        style={{
          display: "grid",
          gridTemplateRows: "auto 1fr auto",
          minHeight: "100vh",
        }}
      >
        <>
          <Header />
          <main className="">{children}</main>
          <Footer />
        </>
      </body>
    </html>
  );
}
